version: "3.9"
services:
  postgresql:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=investments
  backend:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - postgresql